name: AI   |   Artificial Ingredient
title: AI | Artificial Ingredient
description: AI | A smarter way to cook
tags:
  - blog
  - food
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
email: kaylendwyer@gmail.com
# See: https://disqus.com/
# disqus_username: kaylen_dwyer
# Contact Form Setting
# See: https://formspree.io/
# formspree_form_id: formspree_form_id
